version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend 